version: '3.9'

services:
  database:
    image: postgres:14.4
    environment:
      POSTGRES_DB: app
      POSTGRES_PASSWORD: password
      POSTGRES_USER: symfony
    volumes:
      - db-data:/var/lib/postgresql/data:rw

  web:
    build:
      context: ./docker/php
    volumes:
      - ./:/var/www
    working_dir: /var/www


volumes:
  db-data: