account.view:
    methods: [ GET ]
    path: /account/{id<\d+>}
    controller: account.controller::viewAction

account.add:
    methods: [ POST ]
    path: /account/add
    controller: account.controller::addAction

