account.view:
    methods: [ GET ]
    path: /account/{id<\d+>}
    controller: account.controller::viewAction

account.add:
    methods: [ POST ]
    path: /account/add
    controller: account.controller::addAction

account.remove:
    methods: [ DELETE ]
    path: /account/remove/{id<\d+>}
    controller: account.controller::removeAction
